version: '3'

services:
  db:
    image: mariadb
    command: --max_allowed_packet=32505856 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    # environment:
    #   - MYSQL_ROOT_PASSWORD=
    #   - MYSQL_PASSWORD=
    #   - MYSQL_DATABASE=
    #   - MYSQL_USER=
    env_file:
      - bolo-env.env

  web:
    build: ./web
    restart: always
    volumes:
      - bolo:/var/www/html:ro
    # environment:
    #   - VIRTUAL_HOST=
    #   - LETSENCRYPT_HOST=
    #   - LETSENCRYPT_EMAIL=
    depends_on:
      - bolo
    env_file:
      - letsencrypt.env
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # environment:
    #   - ENABLE_IPV6=true
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns: 8.8.8.8
    # environment:
    #   - DEFAULT_EMAIL=
    networks:
      - proxy-tier
    depends_on:
      - proxy

  bolo:
    image: tangcuyu/bolo-solo:latest
    restart: always
    expose:
      - "8080"
    env_file:
      - bolo-env.env
    dns: 8.8.8.8
    command: --listen_port=${LISTEN_PORT} --server_scheme=${SERVER_SCHEME} --server_host=${SERVER_HOST} --server_port=${SERVER_PORT} --lute_http=http://lute:8249
    depends_on:
      - db

  lute:
    image: b3log/lute-http
    restart: always 
    expose: 
      - "8249"

volumes:
  db:
  bolo:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier: